HW09 is completed
alexjurev/hw-otus pull request #10
Opened 2022-10-28 16:45 UTC by alexjurev

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2022-11-01 03:30 UTC, dshemin requested changes

2022-11-01 03:30 UTC, dshemin commented on hw09_struct_validator/validator.go
> +func (v ValidationError) Error() string {
Лучше держать определение типа и методов этого типа рядом. Так легче читать код.

2022-11-01 03:30 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		_, e := res.WriteString(
Посмотрите пожалуйста код WriteString в strings.Builder. Там нет ошибки.

2022-11-01 03:30 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		closure := tag
Не совсем удачный выбор названия для переменной.  Вместо `closure` лучше использовать `tag`

2022-11-01 03:30 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	if t.Kind() != reflect.Struct {
Лучше сначала проверить входное значение, а уже потом проводить инициализацию.

2022-11-01 03:30 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	switch len(validationErrs) {
Лучше использовать `If` тут. Слишком громоздкая конструкция.

2022-11-01 03:30 UTC, dshemin commented on hw09_struct_validator/validator_test.go
> +		// meta   json.RawMessage
Пожалуйста, верните данное поле обратно в структуру.

2022-11-01 03:30 UTC, dshemin commented on hw09_struct_validator/validator_test.go
> +func TestValidatePositive(t *testing.T) {
Если мы тестируем одну конкретную функцию, то лучше держать все её тесты в рамках одной тестовой функции с помощью `t.Run()`

2022-11-02 20:06 UTC, alexjurev commented
@dshemin добрый вечер!
 поправил замечания, билд зеленый, можно проверять

2022-11-04 11:45 UTC, dshemin approved these changes

2022-11-10 09:42 UTC, merged